#!/usr/bin/env sh

_help()
{
	echo
	echo "Usage: lazywal-cli [OPTION] [PATH_TO_VIDEO]"
	echo "Options:"
	echo "		-h		- Display this message"
	echo "		-r		- Restore last wallpaper"
}
_restore()
{
	file_path=$(cat $HOME/.lazywal)
	xwinwrap -fs -ni -b -nf -un -o 1.0 -debug -- mpv -wid WID --loop --no-audio --no-resume-playback --panscan=1.0 $file_path &
}

if [ $# -lt 1 ]
then
	echo "No options found!"
	Help
	exit 1
fi

while getopts "hr" option; do
	case $option in
		h) # display Help
			_help
			exit;;
		r) # restore wal
			_restore
			exit;;
		*) # Illegal option
			_help
			exit;;
	esac
done

for i in $*; do
	if [ -e $i ]
	then
		file_path=$(realpath $i)
		echo $file_path > $HOME/.lazywal
		xwinwrap -fs -ni -b -nf -un -o 1.0 -debug -- mpv -wid WID --loop --no-audio --no-resume-playback --panscan=1.0 $file_path &
	fi
done
